config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'home/top'
  root 'home#top'
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] 
  namespace :admin do
    resources :users, only: [:index]
    resources :shops
  end
  
  delete '/shops/:id', to: 'shops#destroy', as: 'destroy_shop'
  patch '/reviews/:id/rate' => 'reviews#rate', as: :rate_review
  resources :bookmarks, only: [:index]
  resources :likes, only: [:index]
  resources :shops, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    member do
      get 'reviews'
      post 'bookmark'
      get 'reviews'
      delete :bookmark, as: :delete_bookmark
      post 'like', to: 'likes#create', as: :create_like
      delete 'like', to: 'likes#destroy', as: :delete_like
    end
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy]
  end
  get 'hashtags/:tag', to: 'hashtags#show', as: :hashtag
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :shop

  validates :content, presence: { message: 'コメントを入力してください' }
  validates :rate, presence: { message: '評価もつけてください' }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def create
      @shop = Shop.find(params[:shop_id])
      @comment = @shop.comments.build(comment_params)
      @comment.user = current_user
      @comment.rate = params[:comment][:rate]

      if @comment.save
        flash[:notice] = 'コメントが投稿されました。'
        redirect_to reviews_shop_path(@shop)
      else
        flash[:alert] = @comment.errors.full_messages.map { |msg| msg.gsub(/Content|Rate/, '') }.join(', ')
        redirect_to reviews_shop_path(@shop)
      end
    end 
    
    def new
      @shop = Shop.find(params[:shop_id])
      @comment = @shop.comments.build
    end

    def edit
      @comment = Comment.find(params[:id])
    end
  
    def update
      @comment = Comment.find(params[:id])
      if @comment.update(comment_params)
        redirect_to shop_path(@comment.shop), notice: 'コメントが更新されました。'
      else
        render :edit
      end
    end
    
    def destroy
      Comment.find(params[:id]).destroy
      flash[:notice] = 'コメントが削除されました。'
      redirect_to shop_path(params[:shop_id])
    end

    private

    def comment_params
      params.require(:comment).permit(:content, :rate)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [@shop, @comment], url: shop_comments_path(@shop), local: true) do |form| %>
  <div class="form-group">
    <%= form.label :content, "コメント" %>
    <%= form.text_area :content, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :rate, "評価" %>
    <%= form.number_field :rate, min: 1, max: 5, step: 0.5, class: "form-control" %>
  </div>
  <%= form.submit "コメント投稿", class: "btn btn-primary" %>
<% end %>
  

app/views/comments/edit.html.erb
<%= form_with(model: @comment, url: shop_comment_path(@comment.shop, @comment), method: :patch) do |form| %>
    <div class="form-group">
      <%= form.label :content, "コメント" %>
      <%= form.text_area :content, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= form.label :rate, "評価" %>
      <%= form.number_field :rate, min: 1, max: 5, step: 0.5, class: "form-control" %>
    </div>
    <%= form.submit "更新", class: "btn btn-primary" %>
<% end %>
  