config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'home/top'
  root 'home#top'
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] 
  namespace :admin do
    resources :users, only: [:index]
    resources :shops
  end
  
  delete '/shops/:id', to: 'shops#destroy', as: 'destroy_shop'
  patch '/reviews/:id/rate' => 'reviews#rate', as: :rate_review
  resources :bookmarks, only: [:index]
  resources :likes, only: [:index]
  resources :shops, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    member do
      get 'reviews'
      post 'bookmark'
      get 'reviews'
      delete :bookmark, as: :delete_bookmark
      post 'like', to: 'likes#create', as: :create_like
      delete 'like', to: 'likes#destroy', as: :delete_like
    end
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy]
  end
  get 'hashtags/:tag', to: 'hashtags#show', as: :hashtag
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
require 'open-uri'
require 'json'

class Shop < ApplicationRecord
  validates :name, presence: true
  validates :explantory_text, presence: true
  belongs_to :user
  has_one_attached :image
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :reviews
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :users, through: :bookmarks
  accepts_nested_attributes_for :tags, allow_destroy: true
  has_many :likes, dependent: :destroy
  has_one_attached :image

  # タグ名をカンマ区切りで受け取って関連付ける
  def tag_names=(names)
    self.tags = names.split(",").map do |name|
      Tag.find_or_create_by(name: name.strip)
    end
  end
    
  # タグ名をカンマ区切りの文字列として返す
  def tag_names
    tags.pluck(:name).join(", ")
  end

  def reviews
    Review.where(shop_id: id)
  end

  def change
    add_column :shops, :star_rating, :float, default: 0
  end

  def update_star_rating
    update_column(:star_rating, reviews.average(:rate))
  end

end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
    before_action :require_admin
    
    def index
      @shops = Shop.where(admin: false)
      if params[:search].present?
        @shops = Shop.where("name LIKE ?", "%#{params[:search]}%")
      else
        @shops = Shop.all
      end
    end

    private

    def require_admin
        unless current_user&.admin?
          flash[:alert] = "管理ユーザーのみアクセスできます"
          redirect_to root_path
        end
    end
  end
  

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
    before_action :set_shop, only: [:show, :edit, :update, :destroy]
  
    def index
      if params[:tag]
        @tag = Tag.find_by(name: params[:tag])
        if @tag
          @shops = @tag.shops.left_joins(:comments).group(:id).order(Arel.sql('AVG(comments.rate) DESC')).page(params[:page]).per(10)
        else
          @shops = Kaminari.paginate_array([]).page(params[:page]).per(10)
        end
      else
        @shops = Shop.left_joins(:comments).group(:id).order(Arel.sql('AVG(comments.rate) DESC')).page(params[:page]).per(10)
      end      
    end
  
    def show
      @shop = Shop.includes(:tags).find(params[:id])
      @tags = @shop.tags
    end
  
    def new
      @shop = Shop.new
    end
  
    def create
      @shop = Shop.new(shop_params)
      @shop.user = current_user
      @shop.image.attach(params[:shop][:image]) if params[:shop][:image]
      tag_names = params[:shop][:tag_names].split(",")

      if @shop.save
        redirect_to shops_path, notice: '店の情報が登録されました'
      else
        render :new
      end
    end
  
    def edit
      @shop = Shop.includes(:tags).find(params[:id])
      @tags = @shop.tags
      @shop.tags.build # 新しいタグのフォーム用
    end
  
    def update
      @shop = Shop.find(params[:id])
      if @shop.update(shop_params)
        redirect_to @shop, notice: '店の情報が更新されました。'
      else
        flash[:alert] = @shop.errors.full_messages.join(", ")
        render :edit
      end
    end
  
    def destroy
      @shop = Shop.find(params[:id])
      @shop.destroy
      redirect_to shops_path, notice: '店の情報が削除されました。'
    end

    def reviews
      @shop = Shop.find(params[:id])
      @comments = @shop.comments
      @reviews = @shop.reviews
      @comment = Comment.new
    end

    def rate
      @review = Review.find(params[:id])
      @review.update(rating: params[:rating].to_i)
      redirect_to @review.shop
    end

    def bookmark
      @shop = Shop.find(params[:id])
      if current_user.bookmarks.exists?(shop: @shop)
        current_user.bookmarks.find_by(shop: @shop).destroy
      else
        current_user.bookmarks.create(shop: @shop)
      end
      redirect_back fallback_location: root_path
    end
  
    private
  
    def set_shop
      @shop = Shop.find(params[:id])
    end
  
    def shop_params
      params.require(:shop).permit(:name, :explantory_text, :completed, :image, :url, :address, :tag_names, tags_attributes: [:id, :name, :_destroy])
    end
  end
  

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/edit.html.erb
<% provide(:title, @shop.name) %>
<h3>編集ページ<h3>
<% if flash[:alert].present? %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>

<div class="shop_form">
  <%= form_with(model: @shop, url: shop_path(@shop), method: :patch) do |form| %>
    <div class="form_row">
      <%= form.label :name, "店名" %>
      <%= form.text_field :name %>
    </div>

    <div class="form_row">
      <%= form.label :explantory_text, "説明" %>
      <%= form.text_area :explantory_text %>
    </div>

    <div class="form_row">
      <%= form.label :url, "店のURL" %>
      <%= form.text_field :url %>
    </div>

    <div class="form_row">
      <%= form.label :address, "住所" %>
      <%= form.text_field :address %>
    </div>

    <div class="form_row">
      <%= form.label :image, "画像" %>
      <%= form.file_field :image %>
    </div>

    <%= form.fields_for :tags do |tag_form| %>
      <div class="tag_row">
        <%= tag_form.label :name, "タグ" %>
        <%= tag_form.text_field :name %>
        <%= tag_form.check_box :_destroy %>
        <%= tag_form.label :_destroy, "削除" %>
      </div>
    <% end %>

    <div class="submit_btn">
      <%= form.submit "更新" %>
    </div>

    <%= link_to "詳細ページに戻る", shop_path(@shop) %>
  <% end %>
</div>

app/views/shops/index.html.erb
<% content_for(:title, t('.title')) %>
<%= link_to '新規作成', new_shop_path %>
<h1><%= t '.title' %></h1>

<div class="shop-list">
  <%= form_tag shops_path, method: :get, class: 'shop-search-form' do %>
    <%= text_field_tag :tag, params[:tag], placeholder: 'タグを入力してください' %>
    <%= submit_tag '検索' %>
  <% end %>

  <div class="pagination-container custom-pagination">
    <%= paginate @shops %>
  </div>


  <% @shops.each do |shop| %>
    <div class="shop-tile">
      <h2><%= shop.name %></h2>
      <div class="top_image">
        <% if shop.image.attached? %>
          <%= image_tag url_for(shop.image) %>
        <% else %>
          <p>No image available</p>
        <% end %>
      </div>
      <% text = shop.explantory_text %>
      <% limit = 30 %>
  
      <% if text.length > limit %>
        <% truncated_text = text[0...limit] + "..." %>
      <% else %>
        <% truncated_text = text %>
      <% end %>
  
      <p class="list_text"><%= truncated_text %></p>
      <div class="tags">
        <%= shop.tags.pluck(:name).join(', ') %>
      </div>
      <%= link_to "詳細", shop_path(shop) %>
      <div class="bookmark_btn">
        <% if current_user.bookmarks.exists?(shop_id: shop.id) %>
          <%= link_to delete_bookmark_shop_path(shop), method: :delete, class: "bookmark-btn" do %>
            <i class="fas fa-star bookmarked"></i>
          <% end %>
        <% else %>
          <%= link_to bookmark_shop_path(shop), method: :post, class: "bookmark-btn" do %>
            <i class="far fa-star"></i>
          <% end %>
        <% end %>
      </div>
      <div class="like-btn">
        <% if current_user.likes.exists?(shop_id: shop.id) %>
          <%= link_to delete_like_shop_path(shop), method: :delete, class: "unlike-link" do %>
            <i class="fas fa-heart liked"></i> いいね解除
          <% end %>
        <% else %>
          <%= link_to create_like_shop_path(shop), method: :post, class: "like-link" do %>
            <i class="far fa-heart"></i> いいね
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/shops/new.html.erb
<% content_for(:title, t('.title')) %>
<h1><%= t '.title' %></h1>
<div class="shop_form">
  <%= form_with(model: @shop, url: shops_path, local: true) do |form| %>
    <div class="shop_input">
      <%= form.label :name, "店名" %>
      <%= form.text_field :name %>
    </div>

    <div class="shop_input">
      <%= form.label :explantory_text, "説明" %>
      <%= form.text_area :explantory_text %>
    </div>

    <div class="shop_input">
      <%= form.label :url, "店のURL" %>
      <%= form.text_field :url %>
    </div>

    <div class="shop_input">
      <%= form.label :address, "住所" %>
      <%= form.text_field :address %>
    </div>

    <div class="shop_input">
      <%= form.label :image, "イメージ" %>
      <%= form.file_field :image %>
      <%= image_tag @shop.image if @shop.image.attached? %>
    </div>

    <div class="shop_input">
      <%= form.label :tag_names, "タグ（カンマ区切り）" %>
      <%= form.text_field :tag_names, id: "tag_names_input", placeholder: "タグを入力してください" %>
    </div>

    <div>
      <%= form.submit "作成" %>
    </div>
  <% end %>
</div>

app/views/shops/reviews.html.erb
<div class="shop-details">
  <h1><%= @shop.name %></h1>
  <p><%= @shop.address %></p>
  <p><a href="<%= @shop.url %>"><%= @shop.url %></a></p>
  <%= render 'comments/form' %> <!-- コメントフォームを追加 -->
  <table class="comment_list">
  <tbody>
    <% @comments.each do |comment| %>
    <tr>
      
      <td><%= comment.user.name %></td>
      <td><%= comment.content %></td>
      <td>
        <% if comment.rate.present? %>
          <% rating = comment.rate.floor %>
          <% half_star = (comment.rate - rating) >= 0.5 %>
          <% empty_star = 5 - rating - (half_star ? 1 : 0) %>
          <% rating.times do %>
            <%= image_tag("star-on.png", class: "star") %>
          <% end %>
          <% if half_star %>
            <%= image_tag("star-half.png", class: "star") %>
          <% end %>
          <% empty_star.times do %>
            <%= image_tag("star-off.png", class: "star") %>
          <% end %>
        <% end %>
      </td>
      <td>
        <% if comment.user == current_user %>
          <%= link_to "削除", shop_comment_path(comment.shop, comment), method: :delete, class: "btn btn-sm btn-danger p-0 p-1", style: "font-size: 8px;" %>
          <%= link_to "編集", edit_shop_comment_path(comment.shop, comment), class: "btn btn-sm btn-primary p-0 p-1", style: "font-size: 8px;" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
  </table>
  <% if @review %>
    <%= render 'reviews/rating_form', review: @review %> <!-- 評価入力用のフォームを追加 -->
  <% end %>
  <%= link_to "詳細ページに戻る", shop_path(@shop) %>
</div>

app/views/shops/show.html.erb
<% provide(:title, @shop.name) %>
<h1><%= @shop.name %></h1>
<div class="btn_list">
  <% if current_user && current_user == @shop.user %>
    <div class="edit_btn">
      <%= link_to '編集', edit_shop_path(@shop) %>
    </div>
    <div class="del_btn">
      <%= link_to '削除', shop_path(@shop), method: :delete, data: { confirm: '本当に削除しますか？' } %>
    </div>
  <% end %>
  <div class="bookmark_btn">
    <% if current_user.bookmarks.exists?(shop_id: @shop.id) %>
      <%= link_to delete_bookmark_shop_path(@shop), method: :delete, class: "bookmark-btn" do %>
        <i class="fas fa-star bookmarked"></i>
      <% end %>
    <% else %>
      <%= button_to bookmark_shop_path(@shop), method: :post, class: "bookmark-btn" do %>
        <i class="far fa-star"></i>
      <% end %>
    <% end %>
  </div>
</div>

<div class="shop-details">
  <div class="shop-image">
    <% if @shop.image.attached? %>
      <%= image_tag rails_blob_url(@shop.image) %>
    <% end %>
  </div>
  <div class="shop-info">
    <p class="shop_text"><%= @shop.explantory_text %></p>
    <p>マップはこちら：<a class="map_link" href="<%= google_maps_link(@shop.address) %>" target="_blank"><%= @shop.address %></a></p>
    <p><a href="<%= @shop.url %>"><%= @shop.url %></a></p>
    <div class="tags">
      <% @tags.each do |tag| %>
        <% hashtag_name = tag.name.gsub("#", "") %>
        <span class="tag"><%= link_to "##{tag.name}", hashtag_path(tag: tag.name) %></span>
      <% end %>
    </div>
    <p>投稿者: <%= @shop.user.name if @shop.user %></p>
    <%= link_to 'レビューページへ', reviews_shop_path(@shop) %>
    <%= link_to "一覧に戻る", shops_path %>
  </div>
</div>