config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'home/top'
  root 'home#top'
  get 'login', to: "sessions#new"
  post 'login', to: "sessions#create"
  delete 'logout', to: "sessions#destroy"
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy] 
  namespace :admin do
    resources :users, only: [:index]
    resources :shops
  end
  
  delete '/shops/:id', to: 'shops#destroy', as: 'destroy_shop'
  patch '/reviews/:id/rate' => 'reviews#rate', as: :rate_review
  resources :bookmarks, only: [:index]
  resources :likes, only: [:index]
  resources :shops, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    member do
      get 'reviews'
      post 'bookmark'
      get 'reviews'
      delete :bookmark, as: :delete_bookmark
      post 'like', to: 'likes#create', as: :create_like
      delete 'like', to: 'likes#destroy', as: :delete_like
    end
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :likes, only: [:create, :destroy]
    resources :tags, only: [:create, :destroy]
  end
  get 'hashtags/:tag', to: 'hashtags#show', as: :hashtag
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_header_admin.html.erb
<div class="header">   
  <nav class="nav-menu">
    <ul>
      <li><%= link_to (t 'defaults.home'), root_path %></li>
      <li><%= link_to (t 'defaults.profile'), user_path(current_user) %></li>
      <li><%= link_to 'ショップ一覧', shops_path %></li>
      <li><%= link_to 'ブックマーク一覧', bookmarks_path %></li>
      <li><%= link_to 'いいね！をしたお店一覧', likes_path %></li>
      <li><%= link_to 'ユーザー一覧', admin_users_path %></li>
      <li><%= link_to (t 'defaults.logout'), logout_path, method: :delete %></li>
    </ul>
  </nav>
</div>

app/views/shared/_header_logged_in.html.erb
<div class="header">   
  <nav class="nav-menu">
    <ul>
      <li><%= link_to (t 'defaults.home'), root_path %></li>
      <li><%= link_to (t 'defaults.profile'), user_path(current_user) %></li>
      <li><%= link_to 'ショップ一覧', shops_path %></li>
      <li><%= link_to 'ブックマーク一覧', bookmarks_path %></li>
      <li><%= link_to 'いいね！をしたお店一覧', likes_path %></li>
      <li><%= link_to (t 'defaults.logout'), logout_path, method: :delete %></li>
    </ul>
  </nav>
</div>

app/views/shared/_header_logged_out.html.erb
<div class="header">    
  <nav class="nav-menu">
      <ul>
        <li><%= link_to (t 'defaults.home'), root_path %></li>
        <li><%= link_to (t 'defaults.login'), login_path %></li>
        <li><%= link_to '登録', new_user_path %></li>
      </ul>
  </nav>
</div>